name: CI - Basic Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  lint-bash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Run shellcheck
        run: shellcheck cicd/task1/user-data-ec2.sh